services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      # - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"

  backend-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:fpm
    container_name: rinha-backend-api-1
    restart: unless-stopped
    volumes:
    - ./api/:/var/www/html
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - api-db
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "32MB"

  # backend-api-2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # image: php:fpm
  #   container_name: rinha-backend-api-2
  #   restart: unless-stopped
  #   volumes:
  #   - ./api/:/var/www/html
  #   - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
  #   environment:
  #     - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
  #     - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
  #   depends_on:
  #     - api-db
  #   networks:
  #     - backend
  #     - payment-processor
  #   expose:
  #     - "9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.4"          
  #         memory: "64MB"

  # backend-daemon:
  #   build:
  #     context: .
  #     dockerfile: daemon.Dockerfile
  #   container_name: backend-daemon
  #   restart: unless-stopped
  #   volumes:
  #   - ./daemon/:/srv
  #   - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
  #   environment:
  #     - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
  #     - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
  #   depends_on:
  #     - api-db
  #   networks:
  #     - backend
  #     - payment-processor
  #   ports:
  #     - 8089:80
  #   expose:
  #     - "9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"          
  #         memory: "16MB"
  api-db: 
    image: postgres:17-alpine
    container_name: api-db
    hostname: api-db
    ports:
      - 15432:5432
    networks:
      - backend
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "206MB"

  postgrest-1:
    image: postgrest/postgrest
    container_name: postgrest-1
    hostname: postgrest-1
    ports:
      - "3050:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@api-db:5432/rinha
      PGRST_DB_SCHEMA : "public"
      PGRST_DB_ANON_ROLE : "web_anon"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    networks:
      - backend
    depends_on:
      - api-db
    deploy:
      resources:
        limits:
          cpus: "0.2"          
          memory: "32MB"
  
  postgrest-2:
    image: postgrest/postgrest
    container_name: postgrest-2
    hostname: postgrest-2
    ports:
      - "3051:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@api-db:5432/rinha
      PGRST_DB_SCHEMA : "public"
      PGRST_DB_ANON_ROLE : "web_anon"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    networks:
      - backend
    depends_on:
      - api-db
    deploy:
      resources:
        limits:
          cpus: "0.2"          
          memory: "32MB"

  postgrest-3:
    image: postgrest/postgrest
    container_name: postgrest-3
    hostname: postgrest-3
    ports:
      - "3052:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@api-db:5432/rinha
      PGRST_DB_SCHEMA : "public"
      PGRST_DB_ANON_ROLE : "web_anon"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    networks:
      - backend
    depends_on:
      - api-db
    deploy:
      resources:
        limits:
          cpus: "0.2"          
          memory: "32MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true