services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1600MB"

  backend-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:fpm
    container_name: rinha-backend-api-1
    restart: unless-stopped
    volumes:
    - ./app/:/var/www/html
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - api-db
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "640MB"

  backend-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:fpm
    container_name: rinha-backend-api-2
    restart: unless-stopped
    volumes:
    - ./app/:/var/www/html
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - api-db
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "4.0"          
          memory: "6400MB"

  backend-daemon:
    build:
      context: .
    image: php:zts
    container_name: backend-daemon
    restart: unless-stopped
    volumes:
    - ./daemon/:/var/www/html
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - api-db
    networks:
      - backend
      - payment-processor
    ports:
      - 8089:80
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "4.0"          
          memory: "6400MB"
  api-db: 
    image: postgres:17-alpine
    container_name: api-db
    hostname: api-db
    ports:
      - 15432:5432
    networks:
      - backend
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "6400MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true