services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"

  backend-api-1:
    build: .
    image: php:fpm
    container_name: rinha-backend-api-1
    restart: unless-stopped
    volumes:
    - .:/var/www/html
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "64MB"

  backend-api-2:
    build: .
    image: php:fpm
    container_name: rinha-backend-api-2
    restart: unless-stopped
    volumes:
    - .:/var/www/html
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "64MB"
  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "500",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "64MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true